# Generated by Django 3.0.3 on 2020-05-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200515_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskSlug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskOwner',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
