# Generated by Django 3.0.3 on 2020-05-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200518_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='username',
            new_name='user',
        ),
    ]
