# Generated by Django 3.0.3 on 2020-05-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200518_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='user',
            new_name='taskOwner',
        ),
    ]
